# Generated by Django 6.0.7 on 2026-07-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserconfig',
            options={'ordering': ['run_order', 'name']},
        ),
        migrations.AddField(
            model_name='parserconfig',
            name='run_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='excel_rows_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='skipped_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserrun',
            name='stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('excel_validation', 'Excel validation'), ('database_import', 'Database import'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ParserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('admin', 'Admin'), ('command', 'Command')], default='command', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_parser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_batches', to='parsers.parserconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='parser_exports/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_success', models.BooleanField(default=False)),
                ('validation_error', models.TextField(blank=True)),
                ('parser_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export', to='parsers.parserrun')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parser_exports', to='catalog.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParserQueueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('admin', 'Admin'), ('command', 'Command')], default='admin', max_length=20)),
                ('run_all', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_jobs', to='parsers.parserbatch')),
                ('parser_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_jobs', to='parsers.parserconfig')),
                ('parser_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_job', to='parsers.parserrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
