# Generated by Django 6.0.7 on 2026-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_alter_parserconfig_options_parserconfig_run_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserBatchLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nightly_parser_batch', max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parser batch lock',
                'verbose_name_plural': 'Parser batch locks',
            },
        ),
    ]
