# Generated by Django 6.0.7 on 2026-07-30 08:35

from django.db import migrations, models


def create_parser_batch_lock(apps, schema_editor):
    ParserBatchLock = apps.get_model("parsers", "ParserBatchLock")
    ParserBatchLock.objects.get_or_create(name="nightly_parser_batch")


def remove_parser_batch_lock(apps, schema_editor):
    ParserBatchLock = apps.get_model("parsers", "ParserBatchLock")
    ParserBatchLock.objects.filter(name="nightly_parser_batch").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_alter_parserconfig_options_parserconfig_run_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserBatchLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nightly_parser_batch', max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parser batch lock',
                'verbose_name_plural': 'Parser batch locks',
            },
        ),
        migrations.RunPython(create_parser_batch_lock, remove_parser_batch_lock),
    ]
