# Generated by Django 6.0.7 on 2026-07-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_parserbatchlock'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parserbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('status',), name='unique_running_parser_batch'),
        ),
    ]
