# Generated by Django 6.0.7 on 2026-07-30

from django.db import migrations


def create_parser_batch_lock(apps, schema_editor):
    ParserBatchLock = apps.get_model("parsers", "ParserBatchLock")
    ParserBatchLock.objects.get_or_create(name="nightly_parser_batch")


def remove_parser_batch_lock(apps, schema_editor):
    ParserBatchLock = apps.get_model("parsers", "ParserBatchLock")
    ParserBatchLock.objects.filter(name="nightly_parser_batch").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("parsers", "0004_parserbatch_unique_running_parser_batch"),
    ]

    operations = [
        migrations.RunPython(create_parser_batch_lock, remove_parser_batch_lock),
    ]
