# Generated by Django 6.0.7 on 2026-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_create_parser_batch_lock'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parserrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('parser', 'status'), name='unique_running_parser_run_per_parser'),
        ),
    ]
