# Generated by Django 6.0.7 on 2026-08-10 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productoffer_quantity_pricing'),
        ('main', '0003_shoppinglist_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('added', 'Добавлено'), ('removed', 'Удалено'), ('replaced', 'Заменено'), ('purchased', 'Куплено'), ('unpurchased', 'Снята отметка'), ('cleared', 'Список очищен')], db_index=True, max_length=20)),
                ('item_name', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_events', to='catalog.productoffer')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_events', to='catalog.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_clicks', to='catalog.productoffer')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_clicks', to='catalog.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('first_path', models.CharField(blank=True, max_length=500)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('pageviews', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-last_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'visitor_hash'), name='unique_daily_site_visitor')],
            },
        ),
    ]
