# Generated by Django 6.0.7 on 2026-08-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fix_decora_image_urls'),
        ('main', '0004_shoppinglistevent_storeclick_dailysitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='price_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='price_alerts_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='price_alerts_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price_alert_best_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_alert_snapshots', to='catalog.productoffer'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price_alert_best_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price_alert_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='price_alert_source_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
