# Generated by Django 6.0.7 on 2026-08-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_fix_decora_image_urls'),
        ('main', '0005_shoppinglist_price_alerts_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.PositiveIntegerField()),
                ('quantity_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('closed', 'Закрыта'), ('expired', 'Истекла')], db_index=True, default='open', max_length=20)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_purchases', to='catalog.productoffer')),
            ],
            options={
                'ordering': ['-last_activity_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupPurchaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.grouppurchase')),
                ('shopping_list_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_purchase_membership', to='main.shoppinglistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_purchase_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupPurchaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.grouppurchase')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_purchase_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='grouppurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('offer',), name='unique_open_group_purchase_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='grouppurchasemember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_purchase_member'),
        ),
        migrations.AddConstraint(
            model_name='grouppurchasemember',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='group_purchase_member_quantity_gte_1'),
        ),
    ]
