# Generated by Django 6.0.7 on 2026-08-12 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_postgresql_search_indexes'),
        ('main', '0007_seed_group_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 9999)), name='shopping_list_item_quantity_range'),
        ),
    ]
