# Generated by Django 6.0.7 on 2026-08-15 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shoppinglistitem_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Запрос')),
                ('normalized_query', models.CharField(blank=True, max_length=500, verbose_name='Нормализованный запрос')),
                ('visitor_hash', models.CharField(db_index=True, max_length=64, verbose_name='Посетитель')),
                ('source', models.CharField(choices=[('search', 'Поиск'), ('catalog', 'Каталог')], db_index=True, max_length=20, verbose_name='Источник')),
                ('language_code', models.CharField(blank=True, max_length=10, verbose_name='Язык')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Найдено результатов')),
                ('candidates_count', models.PositiveIntegerField(default=0, verbose_name='Проверено кандидатов')),
                ('has_results', models.BooleanField(db_index=True, default=False, verbose_name='Есть результаты')),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время поиска')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'поисковый запрос',
                'verbose_name_plural': 'история поисковых запросов',
                'ordering': ['-searched_at', '-id'],
            },
        ),
    ]
