# Generated by Django 6.0.7 on 2026-07-29 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('normalized_brand', models.CharField(blank=True, db_index=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('normalized_model', models.CharField(blank=True, db_index=True, max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.shop')),
            ],
            options={
                'ordering': ['shop__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=150)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('original_name', models.CharField(max_length=500)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('search_text', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.shop')),
            ],
            options={
                'ordering': ['shop__name', 'original_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productoffer')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['shop', 'normalized_name'], name='catalog_pro_shop_id_ff525f_idx'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['shop', 'barcode'], name='catalog_pro_shop_id_b1c432_idx'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['shop', 'sku'], name='catalog_pro_shop_id_6b334e_idx'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['is_active', 'is_available'], name='catalog_pro_is_acti_15e426_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.UniqueConstraint(fields=('shop', 'external_id'), name='unique_offer_external_id_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('shop', 'external_id'), name='unique_category_external_id_per_shop'),
        ),
    ]
