# Generated by Django 6.0.7 on 2026-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='barcode_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
